services:
  - type: web
    name: moveinsync-ws-server
    runtime: node
    rootDir: mock-server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
